name = "ten-proofs"
version = "0.1.0"
keywords = ["math"]
defaultTargets = [
  "MulticolorTriangleRamsey",
  "SpherePacking",
  "MetricCodes",
  "ConnesRigidity",
  "NonSoficGroup",
  "Permanent",
  "ComparatorChallenges",
]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.33.0-rc1"

[[require]]
name = "Comparator"
git = "https://github.com/leanprover/comparator.git"
rev = "v4.33.0-rc1"

[[lean_lib]]
name = "All"

[[lean_lib]]
name = "MulticolorTriangleRamsey"

[[lean_lib]]
name = "SpherePacking"

[[lean_lib]]
name = "MetricCodes"

[[lean_lib]]
name = "ConnesRigidity"

[[lean_lib]]
name = "NonSoficGroup"

[[lean_lib]]
name = "ComparatorChallenges"
roots = [
  "ComparatorChallenges.A_SpherePacking",
  "ComparatorChallenges.B_BinaryCodes",
  "ComparatorChallenges.B_SphericalCodes",
  "ComparatorChallenges.C_PermanentFormulaLowerBound",
  "ComparatorChallenges.D_NonSoficGroup",
  "ComparatorChallenges.E_ConnesRigidity",
  "ComparatorChallenges.I_MulticolorTriangleRamsey",
]

[[lean_lib]]
name = "Permanent"
